# Ultralytics YOLO ğŸš€, GPL-3.0 license
# PASCAL VOC dataset http://host.robots.ox.ac.uk/pascal/VOC by University of Oxford
# Example usage: yolo train data=VOC.yaml
# parent
# â”œâ”€â”€ yolov5
# â””â”€â”€ datasets
#     â””â”€â”€ VOC  â† downloads here (2.8 GB)


# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: E:/Repository/YOLOV8_train/datasets/feed2
train: # train images (relative to 'path')  16551 images
  - ./train
val: # val images (relative to 'path')  4952 images
    ./val
test: # test images (optional)
    ./test
# Classes
names:
  0 : feed
